_BASE_: "/app/detectron2/configs/COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
MODEL:
  WEIGHTS: "/app/weights/faster_rcnn_R_50/model_final.pth"
  DEVICE: "cpu"
  ROI_HEADS:
    NUM_CLASSES: 80
    SCORE_THRESH_TEST: 0.7
    