platform: "pytorch_libtorch"
default_model_filename: "model.ts"
max_batch_size: 0
input [
  {
    name: "image"
    data_type: TYPE_UINT8
    dims: [3, -1, -1]
  }
]
output [
  {
    name: "bboxes"
    data_type: TYPE_FP32
    dims: [-1,4]
  },
  {
    name: "classes"
    data_type: TYPE_INT64
    dims: [-1]
  },
  {
    name: "scores"
    data_type: TYPE_FP32
    dims: [-1]
  },
  {
    name: "shape"
    data_type: TYPE_INT64
    dims: [-1]
  }
]